package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewProjectsJobsReadParams creates a new ProjectsJobsReadParams object
// with the default values initialized.
func NewProjectsJobsReadParams() *ProjectsJobsReadParams {
	var ()
	return &ProjectsJobsReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewProjectsJobsReadParamsWithTimeout creates a new ProjectsJobsReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewProjectsJobsReadParamsWithTimeout(timeout time.Duration) *ProjectsJobsReadParams {
	var ()
	return &ProjectsJobsReadParams{

		timeout: timeout,
	}
}

// NewProjectsJobsReadParamsWithContext creates a new ProjectsJobsReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewProjectsJobsReadParamsWithContext(ctx context.Context) *ProjectsJobsReadParams {
	var ()
	return &ProjectsJobsReadParams{

		Context: ctx,
	}
}

// NewProjectsJobsReadParamsWithHTTPClient creates a new ProjectsJobsReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewProjectsJobsReadParamsWithHTTPClient(client *http.Client) *ProjectsJobsReadParams {
	var ()
	return &ProjectsJobsReadParams{
		HTTPClient: client,
	}
}

/*ProjectsJobsReadParams contains all the parameters to send to the API endpoint
for the projects jobs read operation typically these are written to a http.Request
*/
type ProjectsJobsReadParams struct {

	/*Namespace*/
	Namespace string
	/*ProjectPk*/
	ProjectPk string
	/*Server*/
	Server string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the projects jobs read params
func (o *ProjectsJobsReadParams) WithTimeout(timeout time.Duration) *ProjectsJobsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the projects jobs read params
func (o *ProjectsJobsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the projects jobs read params
func (o *ProjectsJobsReadParams) WithContext(ctx context.Context) *ProjectsJobsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the projects jobs read params
func (o *ProjectsJobsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the projects jobs read params
func (o *ProjectsJobsReadParams) WithHTTPClient(client *http.Client) *ProjectsJobsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the projects jobs read params
func (o *ProjectsJobsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNamespace adds the namespace to the projects jobs read params
func (o *ProjectsJobsReadParams) WithNamespace(namespace string) *ProjectsJobsReadParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the projects jobs read params
func (o *ProjectsJobsReadParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithProjectPk adds the projectPk to the projects jobs read params
func (o *ProjectsJobsReadParams) WithProjectPk(projectPk string) *ProjectsJobsReadParams {
	o.SetProjectPk(projectPk)
	return o
}

// SetProjectPk adds the projectPk to the projects jobs read params
func (o *ProjectsJobsReadParams) SetProjectPk(projectPk string) {
	o.ProjectPk = projectPk
}

// WithServer adds the server to the projects jobs read params
func (o *ProjectsJobsReadParams) WithServer(server string) *ProjectsJobsReadParams {
	o.SetServer(server)
	return o
}

// SetServer adds the server to the projects jobs read params
func (o *ProjectsJobsReadParams) SetServer(server string) {
	o.Server = server
}

// WriteToRequest writes these params to a swagger request
func (o *ProjectsJobsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	// path param project_pk
	if err := r.SetPathParam("project_pk", o.ProjectPk); err != nil {
		return err
	}

	// path param server
	if err := r.SetPathParam("server", o.Server); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
