package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewProjectsDataSourcesUpdateParams creates a new ProjectsDataSourcesUpdateParams object
// with the default values initialized.
func NewProjectsDataSourcesUpdateParams() *ProjectsDataSourcesUpdateParams {
	var ()
	return &ProjectsDataSourcesUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewProjectsDataSourcesUpdateParamsWithTimeout creates a new ProjectsDataSourcesUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewProjectsDataSourcesUpdateParamsWithTimeout(timeout time.Duration) *ProjectsDataSourcesUpdateParams {
	var ()
	return &ProjectsDataSourcesUpdateParams{

		timeout: timeout,
	}
}

// NewProjectsDataSourcesUpdateParamsWithContext creates a new ProjectsDataSourcesUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewProjectsDataSourcesUpdateParamsWithContext(ctx context.Context) *ProjectsDataSourcesUpdateParams {
	var ()
	return &ProjectsDataSourcesUpdateParams{

		Context: ctx,
	}
}

// NewProjectsDataSourcesUpdateParamsWithHTTPClient creates a new ProjectsDataSourcesUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewProjectsDataSourcesUpdateParamsWithHTTPClient(client *http.Client) *ProjectsDataSourcesUpdateParams {
	var ()
	return &ProjectsDataSourcesUpdateParams{
		HTTPClient: client,
	}
}

/*ProjectsDataSourcesUpdateParams contains all the parameters to send to the API endpoint
for the projects data sources update operation typically these are written to a http.Request
*/
type ProjectsDataSourcesUpdateParams struct {

	/*Data*/
	Data ProjectsDataSourcesUpdateBody
	/*Namespace*/
	Namespace string
	/*ProjectPk*/
	ProjectPk string
	/*Server*/
	Server string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the projects data sources update params
func (o *ProjectsDataSourcesUpdateParams) WithTimeout(timeout time.Duration) *ProjectsDataSourcesUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the projects data sources update params
func (o *ProjectsDataSourcesUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the projects data sources update params
func (o *ProjectsDataSourcesUpdateParams) WithContext(ctx context.Context) *ProjectsDataSourcesUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the projects data sources update params
func (o *ProjectsDataSourcesUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the projects data sources update params
func (o *ProjectsDataSourcesUpdateParams) WithHTTPClient(client *http.Client) *ProjectsDataSourcesUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the projects data sources update params
func (o *ProjectsDataSourcesUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the projects data sources update params
func (o *ProjectsDataSourcesUpdateParams) WithData(data ProjectsDataSourcesUpdateBody) *ProjectsDataSourcesUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the projects data sources update params
func (o *ProjectsDataSourcesUpdateParams) SetData(data ProjectsDataSourcesUpdateBody) {
	o.Data = data
}

// WithNamespace adds the namespace to the projects data sources update params
func (o *ProjectsDataSourcesUpdateParams) WithNamespace(namespace string) *ProjectsDataSourcesUpdateParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the projects data sources update params
func (o *ProjectsDataSourcesUpdateParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithProjectPk adds the projectPk to the projects data sources update params
func (o *ProjectsDataSourcesUpdateParams) WithProjectPk(projectPk string) *ProjectsDataSourcesUpdateParams {
	o.SetProjectPk(projectPk)
	return o
}

// SetProjectPk adds the projectPk to the projects data sources update params
func (o *ProjectsDataSourcesUpdateParams) SetProjectPk(projectPk string) {
	o.ProjectPk = projectPk
}

// WithServer adds the server to the projects data sources update params
func (o *ProjectsDataSourcesUpdateParams) WithServer(server string) *ProjectsDataSourcesUpdateParams {
	o.SetServer(server)
	return o
}

// SetServer adds the server to the projects data sources update params
func (o *ProjectsDataSourcesUpdateParams) SetServer(server string) {
	o.Server = server
}

// WriteToRequest writes these params to a swagger request
func (o *ProjectsDataSourcesUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	// path param project_pk
	if err := r.SetPathParam("project_pk", o.ProjectPk); err != nil {
		return err
	}

	// path param server
	if err := r.SetPathParam("server", o.Server); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
