// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewProjectsCollaboratorsListParams creates a new ProjectsCollaboratorsListParams object
// with the default values initialized.
func NewProjectsCollaboratorsListParams() *ProjectsCollaboratorsListParams {
	var ()
	return &ProjectsCollaboratorsListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewProjectsCollaboratorsListParamsWithTimeout creates a new ProjectsCollaboratorsListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewProjectsCollaboratorsListParamsWithTimeout(timeout time.Duration) *ProjectsCollaboratorsListParams {
	var ()
	return &ProjectsCollaboratorsListParams{

		timeout: timeout,
	}
}

// NewProjectsCollaboratorsListParamsWithContext creates a new ProjectsCollaboratorsListParams object
// with the default values initialized, and the ability to set a context for a request
func NewProjectsCollaboratorsListParamsWithContext(ctx context.Context) *ProjectsCollaboratorsListParams {
	var ()
	return &ProjectsCollaboratorsListParams{

		Context: ctx,
	}
}

// NewProjectsCollaboratorsListParamsWithHTTPClient creates a new ProjectsCollaboratorsListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewProjectsCollaboratorsListParamsWithHTTPClient(client *http.Client) *ProjectsCollaboratorsListParams {
	var ()
	return &ProjectsCollaboratorsListParams{
		HTTPClient: client,
	}
}

/*ProjectsCollaboratorsListParams contains all the parameters to send to the API endpoint
for the projects collaborators list operation typically these are written to a http.Request
*/
type ProjectsCollaboratorsListParams struct {

	/*Limit
	  Limit when retrieving items.

	*/
	Limit *string
	/*Namespace
	  User or team name.

	*/
	Namespace string
	/*Offset
	  Offset when retrieving items.

	*/
	Offset *string
	/*Ordering
	  Ordering when retrieving items.

	*/
	Ordering *string
	/*Project
	  Project unique identifier expressed as UUID or name.

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the projects collaborators list params
func (o *ProjectsCollaboratorsListParams) WithTimeout(timeout time.Duration) *ProjectsCollaboratorsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the projects collaborators list params
func (o *ProjectsCollaboratorsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the projects collaborators list params
func (o *ProjectsCollaboratorsListParams) WithContext(ctx context.Context) *ProjectsCollaboratorsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the projects collaborators list params
func (o *ProjectsCollaboratorsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the projects collaborators list params
func (o *ProjectsCollaboratorsListParams) WithHTTPClient(client *http.Client) *ProjectsCollaboratorsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the projects collaborators list params
func (o *ProjectsCollaboratorsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the projects collaborators list params
func (o *ProjectsCollaboratorsListParams) WithLimit(limit *string) *ProjectsCollaboratorsListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the projects collaborators list params
func (o *ProjectsCollaboratorsListParams) SetLimit(limit *string) {
	o.Limit = limit
}

// WithNamespace adds the namespace to the projects collaborators list params
func (o *ProjectsCollaboratorsListParams) WithNamespace(namespace string) *ProjectsCollaboratorsListParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the projects collaborators list params
func (o *ProjectsCollaboratorsListParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithOffset adds the offset to the projects collaborators list params
func (o *ProjectsCollaboratorsListParams) WithOffset(offset *string) *ProjectsCollaboratorsListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the projects collaborators list params
func (o *ProjectsCollaboratorsListParams) SetOffset(offset *string) {
	o.Offset = offset
}

// WithOrdering adds the ordering to the projects collaborators list params
func (o *ProjectsCollaboratorsListParams) WithOrdering(ordering *string) *ProjectsCollaboratorsListParams {
	o.SetOrdering(ordering)
	return o
}

// SetOrdering adds the ordering to the projects collaborators list params
func (o *ProjectsCollaboratorsListParams) SetOrdering(ordering *string) {
	o.Ordering = ordering
}

// WithProject adds the project to the projects collaborators list params
func (o *ProjectsCollaboratorsListParams) WithProject(project string) *ProjectsCollaboratorsListParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the projects collaborators list params
func (o *ProjectsCollaboratorsListParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *ProjectsCollaboratorsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit string
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := qrLimit
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset string
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := qrOffset
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Ordering != nil {

		// query param ordering
		var qrOrdering string
		if o.Ordering != nil {
			qrOrdering = *o.Ordering
		}
		qOrdering := qrOrdering
		if qOrdering != "" {
			if err := r.SetQueryParam("ordering", qOrdering); err != nil {
				return err
			}
		}

	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
