// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3Blades/go-sdk/models"
)

// ProjectsSyncedResourcesCreateReader is a Reader for the ProjectsSyncedResourcesCreate structure.
type ProjectsSyncedResourcesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectsSyncedResourcesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewProjectsSyncedResourcesCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewProjectsSyncedResourcesCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewProjectsSyncedResourcesCreateCreated creates a ProjectsSyncedResourcesCreateCreated with default headers values
func NewProjectsSyncedResourcesCreateCreated() *ProjectsSyncedResourcesCreateCreated {
	return &ProjectsSyncedResourcesCreateCreated{}
}

/*ProjectsSyncedResourcesCreateCreated handles this case with default header values.

SyncedResource created.
*/
type ProjectsSyncedResourcesCreateCreated struct {
	Payload *models.SyncedResource
}

func (o *ProjectsSyncedResourcesCreateCreated) Error() string {
	return fmt.Sprintf("[POST /v1/{namespace}/projects/{project_id}/synced-resources/][%d] projectsSyncedResourcesCreateCreated  %+v", 201, o.Payload)
}

func (o *ProjectsSyncedResourcesCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SyncedResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProjectsSyncedResourcesCreateBadRequest creates a ProjectsSyncedResourcesCreateBadRequest with default headers values
func NewProjectsSyncedResourcesCreateBadRequest() *ProjectsSyncedResourcesCreateBadRequest {
	return &ProjectsSyncedResourcesCreateBadRequest{}
}

/*ProjectsSyncedResourcesCreateBadRequest handles this case with default header values.

Invalid data supplied.
*/
type ProjectsSyncedResourcesCreateBadRequest struct {
	Payload *models.SyncedResourceError
}

func (o *ProjectsSyncedResourcesCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/{namespace}/projects/{project_id}/synced-resources/][%d] projectsSyncedResourcesCreateBadRequest  %+v", 400, o.Payload)
}

func (o *ProjectsSyncedResourcesCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SyncedResourceError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
