package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkp85/go-sdk/models"
)

// ProjectsJobsStartReader is a Reader for the ProjectsJobsStart structure.
type ProjectsJobsStartReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectsJobsStartReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewProjectsJobsStartCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewProjectsJobsStartBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewProjectsJobsStartCreated creates a ProjectsJobsStartCreated with default headers values
func NewProjectsJobsStartCreated() *ProjectsJobsStartCreated {
	return &ProjectsJobsStartCreated{}
}

/*ProjectsJobsStartCreated handles this case with default header values.

Job created
*/
type ProjectsJobsStartCreated struct {
	Payload *models.Job
}

func (o *ProjectsJobsStartCreated) Error() string {
	return fmt.Sprintf("[POST /api/v0/{namespace}/projects/{project_pk}/jobs/{server}/start/][%d] projectsJobsStartCreated  %+v", 201, o.Payload)
}

func (o *ProjectsJobsStartCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Job)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProjectsJobsStartBadRequest creates a ProjectsJobsStartBadRequest with default headers values
func NewProjectsJobsStartBadRequest() *ProjectsJobsStartBadRequest {
	return &ProjectsJobsStartBadRequest{}
}

/*ProjectsJobsStartBadRequest handles this case with default header values.

Invalid data supplied
*/
type ProjectsJobsStartBadRequest struct {
}

func (o *ProjectsJobsStartBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v0/{namespace}/projects/{project_pk}/jobs/{server}/start/][%d] projectsJobsStartBadRequest ", 400)
}

func (o *ProjectsJobsStartBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*ProjectsJobsStartBody projects jobs start body
swagger:model ProjectsJobsStartBody
*/
type ProjectsJobsStartBody struct {

	// method
	Method string `json:"method,omitempty"`

	// script
	// Required: true
	Script *string `json:"script"`

	// server
	// Required: true
	Server interface{} `json:"server"`
}
