// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3Blades/go-sdk/models"
)

// ProjectsServersStatsCreateReader is a Reader for the ProjectsServersStatsCreate structure.
type ProjectsServersStatsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectsServersStatsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewProjectsServersStatsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewProjectsServersStatsCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewProjectsServersStatsCreateCreated creates a ProjectsServersStatsCreateCreated with default headers values
func NewProjectsServersStatsCreateCreated() *ProjectsServersStatsCreateCreated {
	return &ProjectsServersStatsCreateCreated{}
}

/*ProjectsServersStatsCreateCreated handles this case with default header values.

ServerStatistics created
*/
type ProjectsServersStatsCreateCreated struct {
	Payload *models.ServerStatistics
}

func (o *ProjectsServersStatsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /v1/{namespace}/projects/{project_id}/servers/{server_id}/stats/][%d] projectsServersStatsCreateCreated  %+v", 201, o.Payload)
}

func (o *ProjectsServersStatsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerStatistics)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProjectsServersStatsCreateBadRequest creates a ProjectsServersStatsCreateBadRequest with default headers values
func NewProjectsServersStatsCreateBadRequest() *ProjectsServersStatsCreateBadRequest {
	return &ProjectsServersStatsCreateBadRequest{}
}

/*ProjectsServersStatsCreateBadRequest handles this case with default header values.

Invalid data supplied
*/
type ProjectsServersStatsCreateBadRequest struct {
	Payload *models.ServerStatisticsError
}

func (o *ProjectsServersStatsCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/{namespace}/projects/{project_id}/servers/{server_id}/stats/][%d] projectsServersStatsCreateBadRequest  %+v", 400, o.Payload)
}

func (o *ProjectsServersStatsCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerStatisticsError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
