package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3Blades/go-sdk/models"
)

// ProjectsFilesPartialUpdateReader is a Reader for the ProjectsFilesPartialUpdate structure.
type ProjectsFilesPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectsFilesPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewProjectsFilesPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewProjectsFilesPartialUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewProjectsFilesPartialUpdateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewProjectsFilesPartialUpdateOK creates a ProjectsFilesPartialUpdateOK with default headers values
func NewProjectsFilesPartialUpdateOK() *ProjectsFilesPartialUpdateOK {
	return &ProjectsFilesPartialUpdateOK{}
}

/*ProjectsFilesPartialUpdateOK handles this case with default header values.

File updated
*/
type ProjectsFilesPartialUpdateOK struct {
	Payload *models.File
}

func (o *ProjectsFilesPartialUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /api/v0/{namespace}/projects/{project_pk}/files/{id}/][%d] projectsFilesPartialUpdateOK  %+v", 200, o.Payload)
}

func (o *ProjectsFilesPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.File)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProjectsFilesPartialUpdateBadRequest creates a ProjectsFilesPartialUpdateBadRequest with default headers values
func NewProjectsFilesPartialUpdateBadRequest() *ProjectsFilesPartialUpdateBadRequest {
	return &ProjectsFilesPartialUpdateBadRequest{}
}

/*ProjectsFilesPartialUpdateBadRequest handles this case with default header values.

Invalid data supplied
*/
type ProjectsFilesPartialUpdateBadRequest struct {
}

func (o *ProjectsFilesPartialUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PATCH /api/v0/{namespace}/projects/{project_pk}/files/{id}/][%d] projectsFilesPartialUpdateBadRequest ", 400)
}

func (o *ProjectsFilesPartialUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewProjectsFilesPartialUpdateNotFound creates a ProjectsFilesPartialUpdateNotFound with default headers values
func NewProjectsFilesPartialUpdateNotFound() *ProjectsFilesPartialUpdateNotFound {
	return &ProjectsFilesPartialUpdateNotFound{}
}

/*ProjectsFilesPartialUpdateNotFound handles this case with default header values.

File not found
*/
type ProjectsFilesPartialUpdateNotFound struct {
}

func (o *ProjectsFilesPartialUpdateNotFound) Error() string {
	return fmt.Sprintf("[PATCH /api/v0/{namespace}/projects/{project_pk}/files/{id}/][%d] projectsFilesPartialUpdateNotFound ", 404)
}

func (o *ProjectsFilesPartialUpdateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*ProjectsFilesPartialUpdateBody projects files partial update body
swagger:model ProjectsFilesPartialUpdateBody
*/
type ProjectsFilesPartialUpdateBody struct {

	// author
	Author string `json:"author,omitempty"`

	// content
	Content string `json:"content,omitempty"`

	// encoding
	Encoding string `json:"encoding,omitempty"`

	// path
	Path string `json:"path,omitempty"`

	// project
	Project string `json:"project,omitempty"`

	// public
	Public bool `json:"public,omitempty"`
}
