package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewProjectsJobsDeleteParams creates a new ProjectsJobsDeleteParams object
// with the default values initialized.
func NewProjectsJobsDeleteParams() *ProjectsJobsDeleteParams {
	var ()
	return &ProjectsJobsDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewProjectsJobsDeleteParamsWithTimeout creates a new ProjectsJobsDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewProjectsJobsDeleteParamsWithTimeout(timeout time.Duration) *ProjectsJobsDeleteParams {
	var ()
	return &ProjectsJobsDeleteParams{

		timeout: timeout,
	}
}

// NewProjectsJobsDeleteParamsWithContext creates a new ProjectsJobsDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewProjectsJobsDeleteParamsWithContext(ctx context.Context) *ProjectsJobsDeleteParams {
	var ()
	return &ProjectsJobsDeleteParams{

		Context: ctx,
	}
}

// NewProjectsJobsDeleteParamsWithHTTPClient creates a new ProjectsJobsDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewProjectsJobsDeleteParamsWithHTTPClient(client *http.Client) *ProjectsJobsDeleteParams {
	var ()
	return &ProjectsJobsDeleteParams{
		HTTPClient: client,
	}
}

/*ProjectsJobsDeleteParams contains all the parameters to send to the API endpoint
for the projects jobs delete operation typically these are written to a http.Request
*/
type ProjectsJobsDeleteParams struct {

	/*Namespace*/
	Namespace string
	/*ProjectPk*/
	ProjectPk string
	/*Server*/
	Server string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the projects jobs delete params
func (o *ProjectsJobsDeleteParams) WithTimeout(timeout time.Duration) *ProjectsJobsDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the projects jobs delete params
func (o *ProjectsJobsDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the projects jobs delete params
func (o *ProjectsJobsDeleteParams) WithContext(ctx context.Context) *ProjectsJobsDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the projects jobs delete params
func (o *ProjectsJobsDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the projects jobs delete params
func (o *ProjectsJobsDeleteParams) WithHTTPClient(client *http.Client) *ProjectsJobsDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the projects jobs delete params
func (o *ProjectsJobsDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNamespace adds the namespace to the projects jobs delete params
func (o *ProjectsJobsDeleteParams) WithNamespace(namespace string) *ProjectsJobsDeleteParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the projects jobs delete params
func (o *ProjectsJobsDeleteParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithProjectPk adds the projectPk to the projects jobs delete params
func (o *ProjectsJobsDeleteParams) WithProjectPk(projectPk string) *ProjectsJobsDeleteParams {
	o.SetProjectPk(projectPk)
	return o
}

// SetProjectPk adds the projectPk to the projects jobs delete params
func (o *ProjectsJobsDeleteParams) SetProjectPk(projectPk string) {
	o.ProjectPk = projectPk
}

// WithServer adds the server to the projects jobs delete params
func (o *ProjectsJobsDeleteParams) WithServer(server string) *ProjectsJobsDeleteParams {
	o.SetServer(server)
	return o
}

// SetServer adds the server to the projects jobs delete params
func (o *ProjectsJobsDeleteParams) SetServer(server string) {
	o.Server = server
}

// WriteToRequest writes these params to a swagger request
func (o *ProjectsJobsDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	// path param project_pk
	if err := r.SetPathParam("project_pk", o.ProjectPk); err != nil {
		return err
	}

	// path param server
	if err := r.SetPathParam("server", o.Server); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
