package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewProjectsFilesCreateParams creates a new ProjectsFilesCreateParams object
// with the default values initialized.
func NewProjectsFilesCreateParams() *ProjectsFilesCreateParams {
	var ()
	return &ProjectsFilesCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewProjectsFilesCreateParamsWithTimeout creates a new ProjectsFilesCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewProjectsFilesCreateParamsWithTimeout(timeout time.Duration) *ProjectsFilesCreateParams {
	var ()
	return &ProjectsFilesCreateParams{

		timeout: timeout,
	}
}

// NewProjectsFilesCreateParamsWithContext creates a new ProjectsFilesCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewProjectsFilesCreateParamsWithContext(ctx context.Context) *ProjectsFilesCreateParams {
	var ()
	return &ProjectsFilesCreateParams{

		Context: ctx,
	}
}

// NewProjectsFilesCreateParamsWithHTTPClient creates a new ProjectsFilesCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewProjectsFilesCreateParamsWithHTTPClient(client *http.Client) *ProjectsFilesCreateParams {
	var ()
	return &ProjectsFilesCreateParams{
		HTTPClient: client,
	}
}

/*ProjectsFilesCreateParams contains all the parameters to send to the API endpoint
for the projects files create operation typically these are written to a http.Request
*/
type ProjectsFilesCreateParams struct {

	/*Data*/
	Data ProjectsFilesCreateBody
	/*Namespace*/
	Namespace string
	/*ProjectPk*/
	ProjectPk string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the projects files create params
func (o *ProjectsFilesCreateParams) WithTimeout(timeout time.Duration) *ProjectsFilesCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the projects files create params
func (o *ProjectsFilesCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the projects files create params
func (o *ProjectsFilesCreateParams) WithContext(ctx context.Context) *ProjectsFilesCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the projects files create params
func (o *ProjectsFilesCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the projects files create params
func (o *ProjectsFilesCreateParams) WithHTTPClient(client *http.Client) *ProjectsFilesCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the projects files create params
func (o *ProjectsFilesCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the projects files create params
func (o *ProjectsFilesCreateParams) WithData(data ProjectsFilesCreateBody) *ProjectsFilesCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the projects files create params
func (o *ProjectsFilesCreateParams) SetData(data ProjectsFilesCreateBody) {
	o.Data = data
}

// WithNamespace adds the namespace to the projects files create params
func (o *ProjectsFilesCreateParams) WithNamespace(namespace string) *ProjectsFilesCreateParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the projects files create params
func (o *ProjectsFilesCreateParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithProjectPk adds the projectPk to the projects files create params
func (o *ProjectsFilesCreateParams) WithProjectPk(projectPk string) *ProjectsFilesCreateParams {
	o.SetProjectPk(projectPk)
	return o
}

// SetProjectPk adds the projectPk to the projects files create params
func (o *ProjectsFilesCreateParams) SetProjectPk(projectPk string) {
	o.ProjectPk = projectPk
}

// WriteToRequest writes these params to a swagger request
func (o *ProjectsFilesCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	// path param project_pk
	if err := r.SetPathParam("project_pk", o.ProjectPk); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
