package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewProjectsServersRunStatsCreateParams creates a new ProjectsServersRunStatsCreateParams object
// with the default values initialized.
func NewProjectsServersRunStatsCreateParams() *ProjectsServersRunStatsCreateParams {
	var ()
	return &ProjectsServersRunStatsCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewProjectsServersRunStatsCreateParamsWithTimeout creates a new ProjectsServersRunStatsCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewProjectsServersRunStatsCreateParamsWithTimeout(timeout time.Duration) *ProjectsServersRunStatsCreateParams {
	var ()
	return &ProjectsServersRunStatsCreateParams{

		timeout: timeout,
	}
}

// NewProjectsServersRunStatsCreateParamsWithContext creates a new ProjectsServersRunStatsCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewProjectsServersRunStatsCreateParamsWithContext(ctx context.Context) *ProjectsServersRunStatsCreateParams {
	var ()
	return &ProjectsServersRunStatsCreateParams{

		Context: ctx,
	}
}

// NewProjectsServersRunStatsCreateParamsWithHTTPClient creates a new ProjectsServersRunStatsCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewProjectsServersRunStatsCreateParamsWithHTTPClient(client *http.Client) *ProjectsServersRunStatsCreateParams {
	var ()
	return &ProjectsServersRunStatsCreateParams{
		HTTPClient: client,
	}
}

/*ProjectsServersRunStatsCreateParams contains all the parameters to send to the API endpoint
for the projects servers run stats create operation typically these are written to a http.Request
*/
type ProjectsServersRunStatsCreateParams struct {

	/*Data*/
	Data ProjectsServersRunStatsCreateBody
	/*Namespace*/
	Namespace string
	/*ProjectPk*/
	ProjectPk string
	/*ServerPk*/
	ServerPk string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the projects servers run stats create params
func (o *ProjectsServersRunStatsCreateParams) WithTimeout(timeout time.Duration) *ProjectsServersRunStatsCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the projects servers run stats create params
func (o *ProjectsServersRunStatsCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the projects servers run stats create params
func (o *ProjectsServersRunStatsCreateParams) WithContext(ctx context.Context) *ProjectsServersRunStatsCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the projects servers run stats create params
func (o *ProjectsServersRunStatsCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the projects servers run stats create params
func (o *ProjectsServersRunStatsCreateParams) WithHTTPClient(client *http.Client) *ProjectsServersRunStatsCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the projects servers run stats create params
func (o *ProjectsServersRunStatsCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the projects servers run stats create params
func (o *ProjectsServersRunStatsCreateParams) WithData(data ProjectsServersRunStatsCreateBody) *ProjectsServersRunStatsCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the projects servers run stats create params
func (o *ProjectsServersRunStatsCreateParams) SetData(data ProjectsServersRunStatsCreateBody) {
	o.Data = data
}

// WithNamespace adds the namespace to the projects servers run stats create params
func (o *ProjectsServersRunStatsCreateParams) WithNamespace(namespace string) *ProjectsServersRunStatsCreateParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the projects servers run stats create params
func (o *ProjectsServersRunStatsCreateParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithProjectPk adds the projectPk to the projects servers run stats create params
func (o *ProjectsServersRunStatsCreateParams) WithProjectPk(projectPk string) *ProjectsServersRunStatsCreateParams {
	o.SetProjectPk(projectPk)
	return o
}

// SetProjectPk adds the projectPk to the projects servers run stats create params
func (o *ProjectsServersRunStatsCreateParams) SetProjectPk(projectPk string) {
	o.ProjectPk = projectPk
}

// WithServerPk adds the serverPk to the projects servers run stats create params
func (o *ProjectsServersRunStatsCreateParams) WithServerPk(serverPk string) *ProjectsServersRunStatsCreateParams {
	o.SetServerPk(serverPk)
	return o
}

// SetServerPk adds the serverPk to the projects servers run stats create params
func (o *ProjectsServersRunStatsCreateParams) SetServerPk(serverPk string) {
	o.ServerPk = serverPk
}

// WriteToRequest writes these params to a swagger request
func (o *ProjectsServersRunStatsCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	// path param project_pk
	if err := r.SetPathParam("project_pk", o.ProjectPk); err != nil {
		return err
	}

	// path param server_pk
	if err := r.SetPathParam("server_pk", o.ServerPk); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
