// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/IllumiDesk/go-sdk/models"
)

// NewServiceTriggerReplaceParams creates a new ServiceTriggerReplaceParams object
// with the default values initialized.
func NewServiceTriggerReplaceParams() *ServiceTriggerReplaceParams {
	var ()
	return &ServiceTriggerReplaceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewServiceTriggerReplaceParamsWithTimeout creates a new ServiceTriggerReplaceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewServiceTriggerReplaceParamsWithTimeout(timeout time.Duration) *ServiceTriggerReplaceParams {
	var ()
	return &ServiceTriggerReplaceParams{

		timeout: timeout,
	}
}

// NewServiceTriggerReplaceParamsWithContext creates a new ServiceTriggerReplaceParams object
// with the default values initialized, and the ability to set a context for a request
func NewServiceTriggerReplaceParamsWithContext(ctx context.Context) *ServiceTriggerReplaceParams {
	var ()
	return &ServiceTriggerReplaceParams{

		Context: ctx,
	}
}

// NewServiceTriggerReplaceParamsWithHTTPClient creates a new ServiceTriggerReplaceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewServiceTriggerReplaceParamsWithHTTPClient(client *http.Client) *ServiceTriggerReplaceParams {
	var ()
	return &ServiceTriggerReplaceParams{
		HTTPClient: client,
	}
}

/*ServiceTriggerReplaceParams contains all the parameters to send to the API endpoint
for the service trigger replace operation typically these are written to a http.Request
*/
type ServiceTriggerReplaceParams struct {

	/*Namespace
	  User or team name.

	*/
	Namespace string
	/*Project
	  Project unique identifier expressed as UUID or name.

	*/
	Project string
	/*Server
	  Server unique identifier expressed as UUID or name.

	*/
	Server string
	/*ServerAction*/
	ServerAction *models.ServerActionData
	/*Trigger
	  Trigger unique identifier.

	*/
	Trigger string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the service trigger replace params
func (o *ServiceTriggerReplaceParams) WithTimeout(timeout time.Duration) *ServiceTriggerReplaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the service trigger replace params
func (o *ServiceTriggerReplaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the service trigger replace params
func (o *ServiceTriggerReplaceParams) WithContext(ctx context.Context) *ServiceTriggerReplaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the service trigger replace params
func (o *ServiceTriggerReplaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the service trigger replace params
func (o *ServiceTriggerReplaceParams) WithHTTPClient(client *http.Client) *ServiceTriggerReplaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the service trigger replace params
func (o *ServiceTriggerReplaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNamespace adds the namespace to the service trigger replace params
func (o *ServiceTriggerReplaceParams) WithNamespace(namespace string) *ServiceTriggerReplaceParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the service trigger replace params
func (o *ServiceTriggerReplaceParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithProject adds the project to the service trigger replace params
func (o *ServiceTriggerReplaceParams) WithProject(project string) *ServiceTriggerReplaceParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the service trigger replace params
func (o *ServiceTriggerReplaceParams) SetProject(project string) {
	o.Project = project
}

// WithServer adds the server to the service trigger replace params
func (o *ServiceTriggerReplaceParams) WithServer(server string) *ServiceTriggerReplaceParams {
	o.SetServer(server)
	return o
}

// SetServer adds the server to the service trigger replace params
func (o *ServiceTriggerReplaceParams) SetServer(server string) {
	o.Server = server
}

// WithServerAction adds the serverAction to the service trigger replace params
func (o *ServiceTriggerReplaceParams) WithServerAction(serverAction *models.ServerActionData) *ServiceTriggerReplaceParams {
	o.SetServerAction(serverAction)
	return o
}

// SetServerAction adds the serverAction to the service trigger replace params
func (o *ServiceTriggerReplaceParams) SetServerAction(serverAction *models.ServerActionData) {
	o.ServerAction = serverAction
}

// WithTrigger adds the trigger to the service trigger replace params
func (o *ServiceTriggerReplaceParams) WithTrigger(trigger string) *ServiceTriggerReplaceParams {
	o.SetTrigger(trigger)
	return o
}

// SetTrigger adds the trigger to the service trigger replace params
func (o *ServiceTriggerReplaceParams) SetTrigger(trigger string) {
	o.Trigger = trigger
}

// WriteToRequest writes these params to a swagger request
func (o *ServiceTriggerReplaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	// path param server
	if err := r.SetPathParam("server", o.Server); err != nil {
		return err
	}

	if o.ServerAction != nil {
		if err := r.SetBodyParam(o.ServerAction); err != nil {
			return err
		}
	}

	// path param trigger
	if err := r.SetPathParam("trigger", o.Trigger); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
