package servers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewServersOptionsResourcesReadParams creates a new ServersOptionsResourcesReadParams object
// with the default values initialized.
func NewServersOptionsResourcesReadParams() *ServersOptionsResourcesReadParams {
	var ()
	return &ServersOptionsResourcesReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewServersOptionsResourcesReadParamsWithTimeout creates a new ServersOptionsResourcesReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewServersOptionsResourcesReadParamsWithTimeout(timeout time.Duration) *ServersOptionsResourcesReadParams {
	var ()
	return &ServersOptionsResourcesReadParams{

		timeout: timeout,
	}
}

// NewServersOptionsResourcesReadParamsWithContext creates a new ServersOptionsResourcesReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewServersOptionsResourcesReadParamsWithContext(ctx context.Context) *ServersOptionsResourcesReadParams {
	var ()
	return &ServersOptionsResourcesReadParams{

		Context: ctx,
	}
}

// NewServersOptionsResourcesReadParamsWithHTTPClient creates a new ServersOptionsResourcesReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewServersOptionsResourcesReadParamsWithHTTPClient(client *http.Client) *ServersOptionsResourcesReadParams {
	var ()
	return &ServersOptionsResourcesReadParams{
		HTTPClient: client,
	}
}

/*ServersOptionsResourcesReadParams contains all the parameters to send to the API endpoint
for the servers options resources read operation typically these are written to a http.Request
*/
type ServersOptionsResourcesReadParams struct {

	/*ID*/
	ID string
	/*Namespace*/
	Namespace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the servers options resources read params
func (o *ServersOptionsResourcesReadParams) WithTimeout(timeout time.Duration) *ServersOptionsResourcesReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the servers options resources read params
func (o *ServersOptionsResourcesReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the servers options resources read params
func (o *ServersOptionsResourcesReadParams) WithContext(ctx context.Context) *ServersOptionsResourcesReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the servers options resources read params
func (o *ServersOptionsResourcesReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the servers options resources read params
func (o *ServersOptionsResourcesReadParams) WithHTTPClient(client *http.Client) *ServersOptionsResourcesReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the servers options resources read params
func (o *ServersOptionsResourcesReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the servers options resources read params
func (o *ServersOptionsResourcesReadParams) WithID(id string) *ServersOptionsResourcesReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the servers options resources read params
func (o *ServersOptionsResourcesReadParams) SetID(id string) {
	o.ID = id
}

// WithNamespace adds the namespace to the servers options resources read params
func (o *ServersOptionsResourcesReadParams) WithNamespace(namespace string) *ServersOptionsResourcesReadParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the servers options resources read params
func (o *ServersOptionsResourcesReadParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WriteToRequest writes these params to a swagger request
func (o *ServersOptionsResourcesReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
