package servers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewServersOptionsTypesListParams creates a new ServersOptionsTypesListParams object
// with the default values initialized.
func NewServersOptionsTypesListParams() *ServersOptionsTypesListParams {
	var ()
	return &ServersOptionsTypesListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewServersOptionsTypesListParamsWithTimeout creates a new ServersOptionsTypesListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewServersOptionsTypesListParamsWithTimeout(timeout time.Duration) *ServersOptionsTypesListParams {
	var ()
	return &ServersOptionsTypesListParams{

		timeout: timeout,
	}
}

// NewServersOptionsTypesListParamsWithContext creates a new ServersOptionsTypesListParams object
// with the default values initialized, and the ability to set a context for a request
func NewServersOptionsTypesListParamsWithContext(ctx context.Context) *ServersOptionsTypesListParams {
	var ()
	return &ServersOptionsTypesListParams{

		Context: ctx,
	}
}

// NewServersOptionsTypesListParamsWithHTTPClient creates a new ServersOptionsTypesListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewServersOptionsTypesListParamsWithHTTPClient(client *http.Client) *ServersOptionsTypesListParams {
	var ()
	return &ServersOptionsTypesListParams{
		HTTPClient: client,
	}
}

/*ServersOptionsTypesListParams contains all the parameters to send to the API endpoint
for the servers options types list operation typically these are written to a http.Request
*/
type ServersOptionsTypesListParams struct {

	/*Limit*/
	Limit *string
	/*Namespace*/
	Namespace string
	/*Offset*/
	Offset *string
	/*Ordering*/
	Ordering *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the servers options types list params
func (o *ServersOptionsTypesListParams) WithTimeout(timeout time.Duration) *ServersOptionsTypesListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the servers options types list params
func (o *ServersOptionsTypesListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the servers options types list params
func (o *ServersOptionsTypesListParams) WithContext(ctx context.Context) *ServersOptionsTypesListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the servers options types list params
func (o *ServersOptionsTypesListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the servers options types list params
func (o *ServersOptionsTypesListParams) WithHTTPClient(client *http.Client) *ServersOptionsTypesListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the servers options types list params
func (o *ServersOptionsTypesListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the servers options types list params
func (o *ServersOptionsTypesListParams) WithLimit(limit *string) *ServersOptionsTypesListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the servers options types list params
func (o *ServersOptionsTypesListParams) SetLimit(limit *string) {
	o.Limit = limit
}

// WithNamespace adds the namespace to the servers options types list params
func (o *ServersOptionsTypesListParams) WithNamespace(namespace string) *ServersOptionsTypesListParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the servers options types list params
func (o *ServersOptionsTypesListParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithOffset adds the offset to the servers options types list params
func (o *ServersOptionsTypesListParams) WithOffset(offset *string) *ServersOptionsTypesListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the servers options types list params
func (o *ServersOptionsTypesListParams) SetOffset(offset *string) {
	o.Offset = offset
}

// WithOrdering adds the ordering to the servers options types list params
func (o *ServersOptionsTypesListParams) WithOrdering(ordering *string) *ServersOptionsTypesListParams {
	o.SetOrdering(ordering)
	return o
}

// SetOrdering adds the ordering to the servers options types list params
func (o *ServersOptionsTypesListParams) SetOrdering(ordering *string) {
	o.Ordering = ordering
}

// WriteToRequest writes these params to a swagger request
func (o *ServersOptionsTypesListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit string
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := qrLimit
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset string
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := qrOffset
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Ordering != nil {

		// query param ordering
		var qrOrdering string
		if o.Ordering != nil {
			qrOrdering = *o.Ordering
		}
		qOrdering := qrOrdering
		if qOrdering != "" {
			if err := r.SetQueryParam("ordering", qOrdering); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
