package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3Blades/go-sdk/models"
)

// UsersIntegrationsCreateReader is a Reader for the UsersIntegrationsCreate structure.
type UsersIntegrationsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UsersIntegrationsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewUsersIntegrationsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUsersIntegrationsCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUsersIntegrationsCreateCreated creates a UsersIntegrationsCreateCreated with default headers values
func NewUsersIntegrationsCreateCreated() *UsersIntegrationsCreateCreated {
	return &UsersIntegrationsCreateCreated{}
}

/*UsersIntegrationsCreateCreated handles this case with default header values.

Integration created
*/
type UsersIntegrationsCreateCreated struct {
	Payload *models.Integration
}

func (o *UsersIntegrationsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v0/{namespace}/users/{user_pk}/integrations/][%d] usersIntegrationsCreateCreated  %+v", 201, o.Payload)
}

func (o *UsersIntegrationsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Integration)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUsersIntegrationsCreateBadRequest creates a UsersIntegrationsCreateBadRequest with default headers values
func NewUsersIntegrationsCreateBadRequest() *UsersIntegrationsCreateBadRequest {
	return &UsersIntegrationsCreateBadRequest{}
}

/*UsersIntegrationsCreateBadRequest handles this case with default header values.

Invalid data supplied
*/
type UsersIntegrationsCreateBadRequest struct {
	Payload UsersIntegrationsCreateBadRequestBody
}

func (o *UsersIntegrationsCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v0/{namespace}/users/{user_pk}/integrations/][%d] usersIntegrationsCreateBadRequest  %+v", 400, o.Payload)
}

func (o *UsersIntegrationsCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*UsersIntegrationsCreateBadRequestBody users integrations create bad request body
swagger:model UsersIntegrationsCreateBadRequestBody
*/
type UsersIntegrationsCreateBadRequestBody struct {

	// extra_data field errors
	// Required: true
	ExtraData []string `json:"extra_data"`

	// Errors not connected to any field
	// Required: true
	NonFieldErrors []string `json:"non_field_errors"`

	// provider field errors
	// Required: true
	Provider []string `json:"provider"`
}

// Validate validates this users integrations create bad request body
func (o *UsersIntegrationsCreateBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateExtraData(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateNonFieldErrors(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateProvider(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UsersIntegrationsCreateBadRequestBody) validateExtraData(formats strfmt.Registry) error {

	if err := validate.Required("usersIntegrationsCreateBadRequest"+"."+"extra_data", "body", o.ExtraData); err != nil {
		return err
	}

	return nil
}

func (o *UsersIntegrationsCreateBadRequestBody) validateNonFieldErrors(formats strfmt.Registry) error {

	if err := validate.Required("usersIntegrationsCreateBadRequest"+"."+"non_field_errors", "body", o.NonFieldErrors); err != nil {
		return err
	}

	return nil
}

func (o *UsersIntegrationsCreateBadRequestBody) validateProvider(formats strfmt.Registry) error {

	if err := validate.Required("usersIntegrationsCreateBadRequest"+"."+"provider", "body", o.Provider); err != nil {
		return err
	}

	return nil
}

/*UsersIntegrationsCreateBody users integrations create body
swagger:model UsersIntegrationsCreateBody
*/
type UsersIntegrationsCreateBody struct {

	// extra data
	ExtraData string `json:"extra_data,omitempty"`

	// provider
	// Required: true
	Provider *string `json:"provider"`
}
