package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkp85/go-sdk/models"
)

// UsersIntegrationsCreateReader is a Reader for the UsersIntegrationsCreate structure.
type UsersIntegrationsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UsersIntegrationsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewUsersIntegrationsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUsersIntegrationsCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUsersIntegrationsCreateCreated creates a UsersIntegrationsCreateCreated with default headers values
func NewUsersIntegrationsCreateCreated() *UsersIntegrationsCreateCreated {
	return &UsersIntegrationsCreateCreated{}
}

/*UsersIntegrationsCreateCreated handles this case with default header values.

Integration created
*/
type UsersIntegrationsCreateCreated struct {
	Payload *models.Integration
}

func (o *UsersIntegrationsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /api/v0/{namespace}/users/{user_pk}/integrations/][%d] usersIntegrationsCreateCreated  %+v", 201, o.Payload)
}

func (o *UsersIntegrationsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Integration)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUsersIntegrationsCreateBadRequest creates a UsersIntegrationsCreateBadRequest with default headers values
func NewUsersIntegrationsCreateBadRequest() *UsersIntegrationsCreateBadRequest {
	return &UsersIntegrationsCreateBadRequest{}
}

/*UsersIntegrationsCreateBadRequest handles this case with default header values.

Invalid data supplied
*/
type UsersIntegrationsCreateBadRequest struct {
}

func (o *UsersIntegrationsCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v0/{namespace}/users/{user_pk}/integrations/][%d] usersIntegrationsCreateBadRequest ", 400)
}

func (o *UsersIntegrationsCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*UsersIntegrationsCreateBody users integrations create body
swagger:model UsersIntegrationsCreateBody
*/
type UsersIntegrationsCreateBody struct {

	// integration email
	// Required: true
	IntegrationEmail *string `json:"integration_email"`

	// provider
	// Required: true
	Provider *string `json:"provider"`

	// scopes
	Scopes string `json:"scopes,omitempty"`
}
