// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3Blades/go-sdk/models"
)

// UsersIntegrationsReplaceReader is a Reader for the UsersIntegrationsReplace structure.
type UsersIntegrationsReplaceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UsersIntegrationsReplaceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUsersIntegrationsReplaceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUsersIntegrationsReplaceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUsersIntegrationsReplaceOK creates a UsersIntegrationsReplaceOK with default headers values
func NewUsersIntegrationsReplaceOK() *UsersIntegrationsReplaceOK {
	return &UsersIntegrationsReplaceOK{}
}

/*UsersIntegrationsReplaceOK handles this case with default header values.

Integration updated.
*/
type UsersIntegrationsReplaceOK struct {
	Payload *models.Integration
}

func (o *UsersIntegrationsReplaceOK) Error() string {
	return fmt.Sprintf("[PUT /v1/users/{user_id}/integrations/{id}/][%d] usersIntegrationsReplaceOK  %+v", 200, o.Payload)
}

func (o *UsersIntegrationsReplaceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Integration)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUsersIntegrationsReplaceBadRequest creates a UsersIntegrationsReplaceBadRequest with default headers values
func NewUsersIntegrationsReplaceBadRequest() *UsersIntegrationsReplaceBadRequest {
	return &UsersIntegrationsReplaceBadRequest{}
}

/*UsersIntegrationsReplaceBadRequest handles this case with default header values.

Invalid data supplied.
*/
type UsersIntegrationsReplaceBadRequest struct {
	Payload *models.IntegrationError
}

func (o *UsersIntegrationsReplaceBadRequest) Error() string {
	return fmt.Sprintf("[PUT /v1/users/{user_id}/integrations/{id}/][%d] usersIntegrationsReplaceBadRequest  %+v", 400, o.Payload)
}

func (o *UsersIntegrationsReplaceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IntegrationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
