package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/IllumiDesk/go-sdk/models"
)

// AuthJwtTokenAuthReader is a Reader for the AuthJwtTokenAuth structure.
type AuthJwtTokenAuthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AuthJwtTokenAuthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewAuthJwtTokenAuthCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewAuthJwtTokenAuthBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAuthJwtTokenAuthCreated creates a AuthJwtTokenAuthCreated with default headers values
func NewAuthJwtTokenAuthCreated() *AuthJwtTokenAuthCreated {
	return &AuthJwtTokenAuthCreated{}
}

/*AuthJwtTokenAuthCreated handles this case with default header values.

JWT created
*/
type AuthJwtTokenAuthCreated struct {
	Payload *models.JWT
}

func (o *AuthJwtTokenAuthCreated) GetPayload() interface{} {
	return o.Payload
}

func (o *AuthJwtTokenAuthCreated) Error() string {
	return fmt.Sprintf("[POST /auth/jwt-token-auth/][%d] authJwtTokenAuthCreated  %+v", 201, o.Payload)
}

func (o *AuthJwtTokenAuthCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JWT)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAuthJwtTokenAuthBadRequest creates a AuthJwtTokenAuthBadRequest with default headers values
func NewAuthJwtTokenAuthBadRequest() *AuthJwtTokenAuthBadRequest {
	return &AuthJwtTokenAuthBadRequest{}
}

/*AuthJwtTokenAuthBadRequest handles this case with default header values.

Invalid data supplied
*/
type AuthJwtTokenAuthBadRequest struct {
	Payload *models.JWTError
}

func (o *AuthJwtTokenAuthBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *AuthJwtTokenAuthBadRequest) Error() string {
	return fmt.Sprintf("[POST /auth/jwt-token-auth/][%d] authJwtTokenAuthBadRequest  %+v", 400, o.Payload)
}

func (o *AuthJwtTokenAuthBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JWTError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
