package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRevokeTokenCreateParams creates a new RevokeTokenCreateParams object
// with the default values initialized.
func NewRevokeTokenCreateParams() *RevokeTokenCreateParams {

	return &RevokeTokenCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRevokeTokenCreateParamsWithTimeout creates a new RevokeTokenCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRevokeTokenCreateParamsWithTimeout(timeout time.Duration) *RevokeTokenCreateParams {

	return &RevokeTokenCreateParams{

		timeout: timeout,
	}
}

// NewRevokeTokenCreateParamsWithContext creates a new RevokeTokenCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewRevokeTokenCreateParamsWithContext(ctx context.Context) *RevokeTokenCreateParams {

	return &RevokeTokenCreateParams{

		Context: ctx,
	}
}

// NewRevokeTokenCreateParamsWithHTTPClient creates a new RevokeTokenCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRevokeTokenCreateParamsWithHTTPClient(client *http.Client) *RevokeTokenCreateParams {

	return &RevokeTokenCreateParams{
		HTTPClient: client,
	}
}

/*RevokeTokenCreateParams contains all the parameters to send to the API endpoint
for the revoke token create operation typically these are written to a http.Request
*/
type RevokeTokenCreateParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the revoke token create params
func (o *RevokeTokenCreateParams) WithTimeout(timeout time.Duration) *RevokeTokenCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the revoke token create params
func (o *RevokeTokenCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the revoke token create params
func (o *RevokeTokenCreateParams) WithContext(ctx context.Context) *RevokeTokenCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the revoke token create params
func (o *RevokeTokenCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the revoke token create params
func (o *RevokeTokenCreateParams) WithHTTPClient(client *http.Client) *RevokeTokenCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the revoke token create params
func (o *RevokeTokenCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *RevokeTokenCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
