package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/IllumiDesk/go-sdk/models"
)

// TeamsReplaceReader is a Reader for the TeamsReplace structure.
type TeamsReplaceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TeamsReplaceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewTeamsReplaceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewTeamsReplaceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTeamsReplaceOK creates a TeamsReplaceOK with default headers values
func NewTeamsReplaceOK() *TeamsReplaceOK {
	return &TeamsReplaceOK{}
}

/*TeamsReplaceOK handles this case with default header values.

Team updated
*/
type TeamsReplaceOK struct {
	Payload *models.Team
}

func (o *TeamsReplaceOK) GetPayload() interface{} {
	return o.Payload
}

func (o *TeamsReplaceOK) Error() string {
	return fmt.Sprintf("[PUT /v1/teams/{team}/][%d] teamsReplaceOK  %+v", 200, o.Payload)
}

func (o *TeamsReplaceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Team)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTeamsReplaceBadRequest creates a TeamsReplaceBadRequest with default headers values
func NewTeamsReplaceBadRequest() *TeamsReplaceBadRequest {
	return &TeamsReplaceBadRequest{}
}

/*TeamsReplaceBadRequest handles this case with default header values.

Invalid data supplied.
*/
type TeamsReplaceBadRequest struct {
	Payload *models.TeamError
}

func (o *TeamsReplaceBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *TeamsReplaceBadRequest) Error() string {
	return fmt.Sprintf("[PUT /v1/teams/{team}/][%d] teamsReplaceBadRequest  %+v", 400, o.Payload)
}

func (o *TeamsReplaceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TeamError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
