// Code generated by go-swagger; DO NOT EDIT.

package billing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3Blades/go-sdk/models"
)

// BillingSubscriptionsReplaceReader is a Reader for the BillingSubscriptionsReplace structure.
type BillingSubscriptionsReplaceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BillingSubscriptionsReplaceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewBillingSubscriptionsReplaceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewBillingSubscriptionsReplaceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewBillingSubscriptionsReplaceOK creates a BillingSubscriptionsReplaceOK with default headers values
func NewBillingSubscriptionsReplaceOK() *BillingSubscriptionsReplaceOK {
	return &BillingSubscriptionsReplaceOK{}
}

/*BillingSubscriptionsReplaceOK handles this case with default header values.

Subscription updated.
*/
type BillingSubscriptionsReplaceOK struct {
	Payload *models.Subscription
}

func (o *BillingSubscriptionsReplaceOK) Error() string {
	return fmt.Sprintf("[PUT /v1/{namespace}/billing/subscriptions/{id}/][%d] billingSubscriptionsReplaceOK  %+v", 200, o.Payload)
}

func (o *BillingSubscriptionsReplaceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Subscription)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBillingSubscriptionsReplaceBadRequest creates a BillingSubscriptionsReplaceBadRequest with default headers values
func NewBillingSubscriptionsReplaceBadRequest() *BillingSubscriptionsReplaceBadRequest {
	return &BillingSubscriptionsReplaceBadRequest{}
}

/*BillingSubscriptionsReplaceBadRequest handles this case with default header values.

Invalid data supplied.
*/
type BillingSubscriptionsReplaceBadRequest struct {
	Payload *models.SubscriptionError
}

func (o *BillingSubscriptionsReplaceBadRequest) Error() string {
	return fmt.Sprintf("[PUT /v1/{namespace}/billing/subscriptions/{id}/][%d] billingSubscriptionsReplaceBadRequest  %+v", 400, o.Payload)
}

func (o *BillingSubscriptionsReplaceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SubscriptionError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
