package billing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/IllumiDesk/go-sdk/models"
)

// BillingCardsReplaceReader is a Reader for the BillingCardsReplace structure.
type BillingCardsReplaceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BillingCardsReplaceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewBillingCardsReplaceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewBillingCardsReplaceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewBillingCardsReplaceOK creates a BillingCardsReplaceOK with default headers values
func NewBillingCardsReplaceOK() *BillingCardsReplaceOK {
	return &BillingCardsReplaceOK{}
}

/*BillingCardsReplaceOK handles this case with default header values.

Card updated
*/
type BillingCardsReplaceOK struct {
	Payload *models.Card
}

func (o *BillingCardsReplaceOK) GetPayload() interface{} {
	return o.Payload
}

func (o *BillingCardsReplaceOK) Error() string {
	return fmt.Sprintf("[PUT /v1/{namespace}/billing/cards/{id}/][%d] billingCardsReplaceOK  %+v", 200, o.Payload)
}

func (o *BillingCardsReplaceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Card)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBillingCardsReplaceBadRequest creates a BillingCardsReplaceBadRequest with default headers values
func NewBillingCardsReplaceBadRequest() *BillingCardsReplaceBadRequest {
	return &BillingCardsReplaceBadRequest{}
}

/*BillingCardsReplaceBadRequest handles this case with default header values.

Invalid data supplied
*/
type BillingCardsReplaceBadRequest struct {
	Payload *models.CardError
}

func (o *BillingCardsReplaceBadRequest) GetPayload() interface{} {
	return o.Payload
}

func (o *BillingCardsReplaceBadRequest) Error() string {
	return fmt.Sprintf("[PUT /v1/{namespace}/billing/cards/{id}/][%d] billingCardsReplaceBadRequest  %+v", 400, o.Payload)
}

func (o *BillingCardsReplaceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
