package billing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3Blades/go-sdk/models"
)

// BillingSubscriptionsUpdateReader is a Reader for the BillingSubscriptionsUpdate structure.
type BillingSubscriptionsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BillingSubscriptionsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewBillingSubscriptionsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewBillingSubscriptionsUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewBillingSubscriptionsUpdateOK creates a BillingSubscriptionsUpdateOK with default headers values
func NewBillingSubscriptionsUpdateOK() *BillingSubscriptionsUpdateOK {
	return &BillingSubscriptionsUpdateOK{}
}

/*BillingSubscriptionsUpdateOK handles this case with default header values.

Subscription updated
*/
type BillingSubscriptionsUpdateOK struct {
	Payload *models.Subscription
}

func (o *BillingSubscriptionsUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /{namespace}/billing/subscriptions/{id}/][%d] billingSubscriptionsUpdateOK  %+v", 200, o.Payload)
}

func (o *BillingSubscriptionsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Subscription)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBillingSubscriptionsUpdateBadRequest creates a BillingSubscriptionsUpdateBadRequest with default headers values
func NewBillingSubscriptionsUpdateBadRequest() *BillingSubscriptionsUpdateBadRequest {
	return &BillingSubscriptionsUpdateBadRequest{}
}

/*BillingSubscriptionsUpdateBadRequest handles this case with default header values.

Invalid data supplied
*/
type BillingSubscriptionsUpdateBadRequest struct {
	Payload BillingSubscriptionsUpdateBadRequestBody
}

func (o *BillingSubscriptionsUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /{namespace}/billing/subscriptions/{id}/][%d] billingSubscriptionsUpdateBadRequest  %+v", 400, o.Payload)
}

func (o *BillingSubscriptionsUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*BillingSubscriptionsUpdateBadRequestBody billing subscriptions update bad request body
swagger:model BillingSubscriptionsUpdateBadRequestBody
*/
type BillingSubscriptionsUpdateBadRequestBody struct {

	// application_fee_percent field errors
	// Required: true
	ApplicationFeePercent []string `json:"application_fee_percent"`

	// cancel_at_period_end field errors
	// Required: true
	CancelAtPeriodEnd []string `json:"cancel_at_period_end"`

	// canceled_at field errors
	// Required: true
	CanceledAt []string `json:"canceled_at"`

	// created field errors
	// Required: true
	Created []string `json:"created"`

	// current_period_end field errors
	// Required: true
	CurrentPeriodEnd []string `json:"current_period_end"`

	// current_period_start field errors
	// Required: true
	CurrentPeriodStart []string `json:"current_period_start"`

	// ended_at field errors
	// Required: true
	EndedAt []string `json:"ended_at"`

	// id field errors
	// Required: true
	ID []string `json:"id"`

	// livemode field errors
	// Required: true
	Livemode []string `json:"livemode"`

	// Errors not connected to any field
	// Required: true
	NonFieldErrors []string `json:"non_field_errors"`

	// plan field errors
	// Required: true
	Plan []string `json:"plan"`

	// quantity field errors
	// Required: true
	Quantity []string `json:"quantity"`

	// start field errors
	// Required: true
	Start []string `json:"start"`

	// status field errors
	// Required: true
	Status []string `json:"status"`

	// stripe_id field errors
	// Required: true
	StripeID []string `json:"stripe_id"`

	// trial_end field errors
	// Required: true
	TrialEnd []string `json:"trial_end"`

	// trial_start field errors
	// Required: true
	TrialStart []string `json:"trial_start"`
}

// Validate validates this billing subscriptions update bad request body
func (o *BillingSubscriptionsUpdateBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateApplicationFeePercent(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateCancelAtPeriodEnd(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateCanceledAt(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateCreated(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateCurrentPeriodEnd(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateCurrentPeriodStart(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateEndedAt(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateLivemode(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateNonFieldErrors(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validatePlan(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateQuantity(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateStart(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateStripeID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateTrialEnd(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateTrialStart(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *BillingSubscriptionsUpdateBadRequestBody) validateApplicationFeePercent(formats strfmt.Registry) error {

	if err := validate.Required("billingSubscriptionsUpdateBadRequest"+"."+"application_fee_percent", "body", o.ApplicationFeePercent); err != nil {
		return err
	}

	return nil
}

func (o *BillingSubscriptionsUpdateBadRequestBody) validateCancelAtPeriodEnd(formats strfmt.Registry) error {

	if err := validate.Required("billingSubscriptionsUpdateBadRequest"+"."+"cancel_at_period_end", "body", o.CancelAtPeriodEnd); err != nil {
		return err
	}

	return nil
}

func (o *BillingSubscriptionsUpdateBadRequestBody) validateCanceledAt(formats strfmt.Registry) error {

	if err := validate.Required("billingSubscriptionsUpdateBadRequest"+"."+"canceled_at", "body", o.CanceledAt); err != nil {
		return err
	}

	return nil
}

func (o *BillingSubscriptionsUpdateBadRequestBody) validateCreated(formats strfmt.Registry) error {

	if err := validate.Required("billingSubscriptionsUpdateBadRequest"+"."+"created", "body", o.Created); err != nil {
		return err
	}

	return nil
}

func (o *BillingSubscriptionsUpdateBadRequestBody) validateCurrentPeriodEnd(formats strfmt.Registry) error {

	if err := validate.Required("billingSubscriptionsUpdateBadRequest"+"."+"current_period_end", "body", o.CurrentPeriodEnd); err != nil {
		return err
	}

	return nil
}

func (o *BillingSubscriptionsUpdateBadRequestBody) validateCurrentPeriodStart(formats strfmt.Registry) error {

	if err := validate.Required("billingSubscriptionsUpdateBadRequest"+"."+"current_period_start", "body", o.CurrentPeriodStart); err != nil {
		return err
	}

	return nil
}

func (o *BillingSubscriptionsUpdateBadRequestBody) validateEndedAt(formats strfmt.Registry) error {

	if err := validate.Required("billingSubscriptionsUpdateBadRequest"+"."+"ended_at", "body", o.EndedAt); err != nil {
		return err
	}

	return nil
}

func (o *BillingSubscriptionsUpdateBadRequestBody) validateID(formats strfmt.Registry) error {

	if err := validate.Required("billingSubscriptionsUpdateBadRequest"+"."+"id", "body", o.ID); err != nil {
		return err
	}

	return nil
}

func (o *BillingSubscriptionsUpdateBadRequestBody) validateLivemode(formats strfmt.Registry) error {

	if err := validate.Required("billingSubscriptionsUpdateBadRequest"+"."+"livemode", "body", o.Livemode); err != nil {
		return err
	}

	return nil
}

func (o *BillingSubscriptionsUpdateBadRequestBody) validateNonFieldErrors(formats strfmt.Registry) error {

	if err := validate.Required("billingSubscriptionsUpdateBadRequest"+"."+"non_field_errors", "body", o.NonFieldErrors); err != nil {
		return err
	}

	return nil
}

func (o *BillingSubscriptionsUpdateBadRequestBody) validatePlan(formats strfmt.Registry) error {

	if err := validate.Required("billingSubscriptionsUpdateBadRequest"+"."+"plan", "body", o.Plan); err != nil {
		return err
	}

	return nil
}

func (o *BillingSubscriptionsUpdateBadRequestBody) validateQuantity(formats strfmt.Registry) error {

	if err := validate.Required("billingSubscriptionsUpdateBadRequest"+"."+"quantity", "body", o.Quantity); err != nil {
		return err
	}

	return nil
}

func (o *BillingSubscriptionsUpdateBadRequestBody) validateStart(formats strfmt.Registry) error {

	if err := validate.Required("billingSubscriptionsUpdateBadRequest"+"."+"start", "body", o.Start); err != nil {
		return err
	}

	return nil
}

func (o *BillingSubscriptionsUpdateBadRequestBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("billingSubscriptionsUpdateBadRequest"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

func (o *BillingSubscriptionsUpdateBadRequestBody) validateStripeID(formats strfmt.Registry) error {

	if err := validate.Required("billingSubscriptionsUpdateBadRequest"+"."+"stripe_id", "body", o.StripeID); err != nil {
		return err
	}

	return nil
}

func (o *BillingSubscriptionsUpdateBadRequestBody) validateTrialEnd(formats strfmt.Registry) error {

	if err := validate.Required("billingSubscriptionsUpdateBadRequest"+"."+"trial_end", "body", o.TrialEnd); err != nil {
		return err
	}

	return nil
}

func (o *BillingSubscriptionsUpdateBadRequestBody) validateTrialStart(formats strfmt.Registry) error {

	if err := validate.Required("billingSubscriptionsUpdateBadRequest"+"."+"trial_start", "body", o.TrialStart); err != nil {
		return err
	}

	return nil
}

/*BillingSubscriptionsUpdateBody billing subscriptions update body
swagger:model BillingSubscriptionsUpdateBody
*/
type BillingSubscriptionsUpdateBody struct {

	// plan
	// Required: true
	Plan *string `json:"plan"`
}
