package billing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewBillingSubscriptionsReadParams creates a new BillingSubscriptionsReadParams object
// with the default values initialized.
func NewBillingSubscriptionsReadParams() *BillingSubscriptionsReadParams {
	var ()
	return &BillingSubscriptionsReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewBillingSubscriptionsReadParamsWithTimeout creates a new BillingSubscriptionsReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewBillingSubscriptionsReadParamsWithTimeout(timeout time.Duration) *BillingSubscriptionsReadParams {
	var ()
	return &BillingSubscriptionsReadParams{

		timeout: timeout,
	}
}

// NewBillingSubscriptionsReadParamsWithContext creates a new BillingSubscriptionsReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewBillingSubscriptionsReadParamsWithContext(ctx context.Context) *BillingSubscriptionsReadParams {
	var ()
	return &BillingSubscriptionsReadParams{

		Context: ctx,
	}
}

// NewBillingSubscriptionsReadParamsWithHTTPClient creates a new BillingSubscriptionsReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewBillingSubscriptionsReadParamsWithHTTPClient(client *http.Client) *BillingSubscriptionsReadParams {
	var ()
	return &BillingSubscriptionsReadParams{
		HTTPClient: client,
	}
}

/*BillingSubscriptionsReadParams contains all the parameters to send to the API endpoint
for the billing subscriptions read operation typically these are written to a http.Request
*/
type BillingSubscriptionsReadParams struct {

	/*ID*/
	ID string
	/*Namespace*/
	Namespace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the billing subscriptions read params
func (o *BillingSubscriptionsReadParams) WithTimeout(timeout time.Duration) *BillingSubscriptionsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the billing subscriptions read params
func (o *BillingSubscriptionsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the billing subscriptions read params
func (o *BillingSubscriptionsReadParams) WithContext(ctx context.Context) *BillingSubscriptionsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the billing subscriptions read params
func (o *BillingSubscriptionsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the billing subscriptions read params
func (o *BillingSubscriptionsReadParams) WithHTTPClient(client *http.Client) *BillingSubscriptionsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the billing subscriptions read params
func (o *BillingSubscriptionsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the billing subscriptions read params
func (o *BillingSubscriptionsReadParams) WithID(id string) *BillingSubscriptionsReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the billing subscriptions read params
func (o *BillingSubscriptionsReadParams) SetID(id string) {
	o.ID = id
}

// WithNamespace adds the namespace to the billing subscriptions read params
func (o *BillingSubscriptionsReadParams) WithNamespace(namespace string) *BillingSubscriptionsReadParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the billing subscriptions read params
func (o *BillingSubscriptionsReadParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WriteToRequest writes these params to a swagger request
func (o *BillingSubscriptionsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
