// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewTeamsBillingInvoiceItemsReadParams creates a new TeamsBillingInvoiceItemsReadParams object
// with the default values initialized.
func NewTeamsBillingInvoiceItemsReadParams() *TeamsBillingInvoiceItemsReadParams {
	var ()
	return &TeamsBillingInvoiceItemsReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTeamsBillingInvoiceItemsReadParamsWithTimeout creates a new TeamsBillingInvoiceItemsReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTeamsBillingInvoiceItemsReadParamsWithTimeout(timeout time.Duration) *TeamsBillingInvoiceItemsReadParams {
	var ()
	return &TeamsBillingInvoiceItemsReadParams{

		timeout: timeout,
	}
}

// NewTeamsBillingInvoiceItemsReadParamsWithContext creates a new TeamsBillingInvoiceItemsReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewTeamsBillingInvoiceItemsReadParamsWithContext(ctx context.Context) *TeamsBillingInvoiceItemsReadParams {
	var ()
	return &TeamsBillingInvoiceItemsReadParams{

		Context: ctx,
	}
}

// NewTeamsBillingInvoiceItemsReadParamsWithHTTPClient creates a new TeamsBillingInvoiceItemsReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTeamsBillingInvoiceItemsReadParamsWithHTTPClient(client *http.Client) *TeamsBillingInvoiceItemsReadParams {
	var ()
	return &TeamsBillingInvoiceItemsReadParams{
		HTTPClient: client,
	}
}

/*TeamsBillingInvoiceItemsReadParams contains all the parameters to send to the API endpoint
for the teams billing invoice items read operation typically these are written to a http.Request
*/
type TeamsBillingInvoiceItemsReadParams struct {

	/*ID
	  InvoiceItem id, expressed as UUID.

	*/
	ID string
	/*InvoiceID
	  Invoice id, expressed as UUID.

	*/
	InvoiceID string
	/*Team
	  Team unique identifier expressed as UUID or name.

	*/
	Team string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the teams billing invoice items read params
func (o *TeamsBillingInvoiceItemsReadParams) WithTimeout(timeout time.Duration) *TeamsBillingInvoiceItemsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the teams billing invoice items read params
func (o *TeamsBillingInvoiceItemsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the teams billing invoice items read params
func (o *TeamsBillingInvoiceItemsReadParams) WithContext(ctx context.Context) *TeamsBillingInvoiceItemsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the teams billing invoice items read params
func (o *TeamsBillingInvoiceItemsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the teams billing invoice items read params
func (o *TeamsBillingInvoiceItemsReadParams) WithHTTPClient(client *http.Client) *TeamsBillingInvoiceItemsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the teams billing invoice items read params
func (o *TeamsBillingInvoiceItemsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the teams billing invoice items read params
func (o *TeamsBillingInvoiceItemsReadParams) WithID(id string) *TeamsBillingInvoiceItemsReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the teams billing invoice items read params
func (o *TeamsBillingInvoiceItemsReadParams) SetID(id string) {
	o.ID = id
}

// WithInvoiceID adds the invoiceID to the teams billing invoice items read params
func (o *TeamsBillingInvoiceItemsReadParams) WithInvoiceID(invoiceID string) *TeamsBillingInvoiceItemsReadParams {
	o.SetInvoiceID(invoiceID)
	return o
}

// SetInvoiceID adds the invoiceId to the teams billing invoice items read params
func (o *TeamsBillingInvoiceItemsReadParams) SetInvoiceID(invoiceID string) {
	o.InvoiceID = invoiceID
}

// WithTeam adds the team to the teams billing invoice items read params
func (o *TeamsBillingInvoiceItemsReadParams) WithTeam(team string) *TeamsBillingInvoiceItemsReadParams {
	o.SetTeam(team)
	return o
}

// SetTeam adds the team to the teams billing invoice items read params
func (o *TeamsBillingInvoiceItemsReadParams) SetTeam(team string) {
	o.Team = team
}

// WriteToRequest writes these params to a swagger request
func (o *TeamsBillingInvoiceItemsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param invoice_id
	if err := r.SetPathParam("invoice_id", o.InvoiceID); err != nil {
		return err
	}

	// path param team
	if err := r.SetPathParam("team", o.Team); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
