package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/IllumiDesk/go-sdk/models"
)

// TeamsBillingInvoiceItemsReadReader is a Reader for the TeamsBillingInvoiceItemsRead structure.
type TeamsBillingInvoiceItemsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TeamsBillingInvoiceItemsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewTeamsBillingInvoiceItemsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewTeamsBillingInvoiceItemsReadNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTeamsBillingInvoiceItemsReadOK creates a TeamsBillingInvoiceItemsReadOK with default headers values
func NewTeamsBillingInvoiceItemsReadOK() *TeamsBillingInvoiceItemsReadOK {
	return &TeamsBillingInvoiceItemsReadOK{}
}

/*TeamsBillingInvoiceItemsReadOK handles this case with default header values.

Team invoiceItem retrieved.
*/
type TeamsBillingInvoiceItemsReadOK struct {
	Payload *models.InvoiceItem
}

func (o *TeamsBillingInvoiceItemsReadOK) GetPayload() interface{} {
	return o.Payload
}

func (o *TeamsBillingInvoiceItemsReadOK) Error() string {
	return fmt.Sprintf("[GET /v1/teams/{team}/billing/invoices/{invoice_id}/invoice-items/{id}][%d] teamsBillingInvoiceItemsReadOK  %+v", 200, o.Payload)
}

func (o *TeamsBillingInvoiceItemsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InvoiceItem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTeamsBillingInvoiceItemsReadNotFound creates a TeamsBillingInvoiceItemsReadNotFound with default headers values
func NewTeamsBillingInvoiceItemsReadNotFound() *TeamsBillingInvoiceItemsReadNotFound {
	return &TeamsBillingInvoiceItemsReadNotFound{}
}

/*TeamsBillingInvoiceItemsReadNotFound handles this case with default header values.

InvoiceItem not found.
*/
type TeamsBillingInvoiceItemsReadNotFound struct {
	Payload *models.NotFound
}

func (o *TeamsBillingInvoiceItemsReadNotFound) GetPayload() interface{} {
	return o.Payload
}

func (o *TeamsBillingInvoiceItemsReadNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/teams/{team}/billing/invoices/{invoice_id}/invoice-items/{id}][%d] teamsBillingInvoiceItemsReadNotFound  %+v", 404, o.Payload)
}

func (o *TeamsBillingInvoiceItemsReadNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NotFound)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
