package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Card card
// swagger:model Card
type Card struct {

	// address city
	AddressCity string `json:"address_city,omitempty"`

	// address country
	AddressCountry string `json:"address_country,omitempty"`

	// address line1
	AddressLine1 string `json:"address_line1,omitempty"`

	// address line1 check
	AddressLine1Check string `json:"address_line1_check,omitempty"`

	// address line2
	AddressLine2 string `json:"address_line2,omitempty"`

	// address state
	AddressState string `json:"address_state,omitempty"`

	// address zip
	AddressZip string `json:"address_zip,omitempty"`

	// address zip check
	AddressZipCheck string `json:"address_zip_check,omitempty"`

	// brand
	Brand string `json:"brand,omitempty"`

	// created
	Created string `json:"created,omitempty"`

	// customer
	Customer string `json:"customer,omitempty"`

	// cvc check
	CvcCheck string `json:"cvc_check,omitempty"`

	// exp month
	ExpMonth int64 `json:"exp_month,omitempty"`

	// exp year
	ExpYear int64 `json:"exp_year,omitempty"`

	// fingerprint
	Fingerprint string `json:"fingerprint,omitempty"`

	// funding
	Funding string `json:"funding,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// last4
	Last4 string `json:"last4,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// stripe id
	StripeID string `json:"stripe_id,omitempty"`

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this card
func (m *Card) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
