// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// NotificationSettingsError notification settings error
// swagger:model NotificationSettingsError
type NotificationSettingsError struct {

	// emails_enabled field errors
	EmailsEnabled bool `json:"emails_enabled,omitempty"`

	// enabled field errors
	Enabled bool `json:"enabled,omitempty"`

	// Errors not connected to any field
	NonFieldErrors []string `json:"non_field_errors"`
}

// Validate validates this notification settings error
func (m *NotificationSettingsError) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNonFieldErrors(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NotificationSettingsError) validateNonFieldErrors(formats strfmt.Registry) error {

	if swag.IsZero(m.NonFieldErrors) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *NotificationSettingsError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NotificationSettingsError) UnmarshalBinary(b []byte) error {
	var res NotificationSettingsError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
