// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ProjectFile project file
// swagger:model ProjectFile
type ProjectFile struct {

	// Data sent as string, in base64 format.
	Content string `json:"content,omitempty"`

	// File unique identifier in UUID format.
	ID string `json:"id,omitempty"`

	// File name and extension.
	Name string `json:"name,omitempty"`

	// File path. Defaults to root (/).
	Path string `json:"path,omitempty"`

	// Project name where file is located.
	// Required: true
	Project *string `json:"project"`
}

// Validate validates this project file
func (m *ProjectFile) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProject(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProjectFile) validateProject(formats strfmt.Registry) error {

	if err := validate.Required("project", "body", m.Project); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProjectFile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectFile) UnmarshalBinary(b []byte) error {
	var res ProjectFile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
