package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ServerRunStatistics server run statistics
// swagger:model ServerRunStatistics
type ServerRunStatistics struct {

	// exit code
	ExitCode int64 `json:"exit_code,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// size
	Size int64 `json:"size,omitempty"`

	// stacktrace
	Stacktrace string `json:"stacktrace,omitempty"`

	// start
	Start string `json:"start,omitempty"`

	// stop
	Stop string `json:"stop,omitempty"`
}

// Validate validates this server run statistics
func (m *ServerRunStatistics) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
