// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ServerConfig server config
// swagger:model ServerConfig
type ServerConfig struct {

	// Command to run
	Command string `json:"command,omitempty"`

	// Server function.
	Function string `json:"function,omitempty"`

	// Server script file.
	Script string `json:"script,omitempty"`

	// Server type.
	Type string `json:"type,omitempty"`
}

// Validate validates this server config
func (m *ServerConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var serverConfigTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["jupyter","restful","cron"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		serverConfigTypeTypePropEnum = append(serverConfigTypeTypePropEnum, v)
	}
}

const (
	// ServerConfigTypeJupyter captures enum value "jupyter"
	ServerConfigTypeJupyter string = "jupyter"
	// ServerConfigTypeRestful captures enum value "restful"
	ServerConfigTypeRestful string = "restful"
	// ServerConfigTypeCron captures enum value "cron"
	ServerConfigTypeCron string = "cron"
)

// prop value enum
func (m *ServerConfig) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, serverConfigTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *ServerConfig) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ServerConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServerConfig) UnmarshalBinary(b []byte) error {
	var res ServerConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
